// flow-typed signature: b3a5fadf9a75f8a9e29c02ad54a2d3cb
// flow-typed version: <<STUB>>/babel_v^6.5.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel/cli.js' {
  declare module.exports: $Exports<'babel/cli'>;
}
declare module 'babel/index' {
  declare module.exports: $Exports<'babel'>;
}
declare module 'babel/index.js' {
  declare module.exports: $Exports<'babel'>;
}
