// flow-typed signature: 8ac568966741c29257b7ab170fe18fe1
// flow-typed version: <<STUB>>/cssbeautify_v^0.3.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssbeautify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssbeautify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cssbeautify/cssbeautify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cssbeautify/cssbeautify.js' {
  declare module.exports: $Exports<'cssbeautify/cssbeautify'>;
}
