// flow-typed signature: ad8d65e2b23766c829aed6f2bf386ea4
// flow-typed version: <<STUB>>/express-http-proxy_v^0.6.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-http-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-http-proxy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-http-proxy/test/app' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-http-proxy/index' {
  declare module.exports: $Exports<'express-http-proxy'>;
}
declare module 'express-http-proxy/index.js' {
  declare module.exports: $Exports<'express-http-proxy'>;
}
declare module 'express-http-proxy/test/app.js' {
  declare module.exports: $Exports<'express-http-proxy/test/app'>;
}
declare module 'express-http-proxy/test/test.js' {
  declare module.exports: $Exports<'express-http-proxy/test/test'>;
}
