// flow-typed signature: 9fc29e1f556e9bf958434180866b3576
// flow-typed version: <<STUB>>/gzip-js_v^0.3.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gzip-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gzip-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gzip-js/bin/gunzip' {
  declare module.exports: any;
}

declare module 'gzip-js/bin/gzip' {
  declare module.exports: any;
}

declare module 'gzip-js/lib/gzip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gzip-js/bin/gunzip.js' {
  declare module.exports: $Exports<'gzip-js/bin/gunzip'>;
}
declare module 'gzip-js/bin/gzip.js' {
  declare module.exports: $Exports<'gzip-js/bin/gzip'>;
}
declare module 'gzip-js/lib/gzip.js' {
  declare module.exports: $Exports<'gzip-js/lib/gzip'>;
}
