// flow-typed signature: 46ba807e47cbf96979d533a9bc6dcd4f
// flow-typed version: <<STUB>>/istanbul_v^1.0.0-alpha.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'istanbul/lib/cli' {
  declare module.exports: any;
}

declare module 'istanbul/lib/command/check-coverage' {
  declare module.exports: any;
}

declare module 'istanbul/lib/command/cover' {
  declare module.exports: any;
}

declare module 'istanbul/lib/command/help' {
  declare module.exports: any;
}

declare module 'istanbul/lib/command/index' {
  declare module.exports: any;
}

declare module 'istanbul/lib/command/instrument' {
  declare module.exports: any;
}

declare module 'istanbul/lib/command/report' {
  declare module.exports: any;
}

declare module 'istanbul/lib/register-plugins' {
  declare module.exports: any;
}

declare module 'istanbul/lib/util/factory' {
  declare module.exports: any;
}

declare module 'istanbul/lib/util/help-formatter' {
  declare module.exports: any;
}

declare module 'istanbul/lib/util/input-error' {
  declare module.exports: any;
}

declare module 'istanbul/lib/util/meta' {
  declare module.exports: any;
}

// Filename aliases
declare module 'istanbul/index' {
  declare module.exports: $Exports<'istanbul'>;
}
declare module 'istanbul/index.js' {
  declare module.exports: $Exports<'istanbul'>;
}
declare module 'istanbul/lib/cli.js' {
  declare module.exports: $Exports<'istanbul/lib/cli'>;
}
declare module 'istanbul/lib/command/check-coverage.js' {
  declare module.exports: $Exports<'istanbul/lib/command/check-coverage'>;
}
declare module 'istanbul/lib/command/cover.js' {
  declare module.exports: $Exports<'istanbul/lib/command/cover'>;
}
declare module 'istanbul/lib/command/help.js' {
  declare module.exports: $Exports<'istanbul/lib/command/help'>;
}
declare module 'istanbul/lib/command/index.js' {
  declare module.exports: $Exports<'istanbul/lib/command/index'>;
}
declare module 'istanbul/lib/command/instrument.js' {
  declare module.exports: $Exports<'istanbul/lib/command/instrument'>;
}
declare module 'istanbul/lib/command/report.js' {
  declare module.exports: $Exports<'istanbul/lib/command/report'>;
}
declare module 'istanbul/lib/register-plugins.js' {
  declare module.exports: $Exports<'istanbul/lib/register-plugins'>;
}
declare module 'istanbul/lib/util/factory.js' {
  declare module.exports: $Exports<'istanbul/lib/util/factory'>;
}
declare module 'istanbul/lib/util/help-formatter.js' {
  declare module.exports: $Exports<'istanbul/lib/util/help-formatter'>;
}
declare module 'istanbul/lib/util/input-error.js' {
  declare module.exports: $Exports<'istanbul/lib/util/input-error'>;
}
declare module 'istanbul/lib/util/meta.js' {
  declare module.exports: $Exports<'istanbul/lib/util/meta'>;
}
