// flow-typed signature: a66e2d278f336bb7defc8483df14f7ff
// flow-typed version: <<STUB>>/rollup_v0.26.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup/bin/handleError' {
  declare module.exports: any;
}

declare module 'rollup/bin/runRollup' {
  declare module.exports: any;
}

declare module 'rollup/bin/showHelp' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup.browser' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup' {
  declare module.exports: any;
}

declare module 'rollup/src/ast/attachScopes' {
  declare module.exports: any;
}

declare module 'rollup/src/ast/conditions' {
  declare module.exports: any;
}

declare module 'rollup/src/ast/create' {
  declare module.exports: any;
}

declare module 'rollup/src/ast/extractNames' {
  declare module.exports: any;
}

declare module 'rollup/src/ast/flatten' {
  declare module.exports: any;
}

declare module 'rollup/src/ast/isFunctionDeclaration' {
  declare module.exports: any;
}

declare module 'rollup/src/ast/isReference' {
  declare module.exports: any;
}

declare module 'rollup/src/ast/modifierNodes' {
  declare module.exports: any;
}

declare module 'rollup/src/ast/Scope' {
  declare module.exports: any;
}

declare module 'rollup/src/banner' {
  declare module.exports: any;
}

declare module 'rollup/src/Bundle' {
  declare module.exports: any;
}

declare module 'rollup/src/Declaration' {
  declare module.exports: any;
}

declare module 'rollup/src/ExternalModule' {
  declare module.exports: any;
}

declare module 'rollup/src/finalisers/amd' {
  declare module.exports: any;
}

declare module 'rollup/src/finalisers/cjs' {
  declare module.exports: any;
}

declare module 'rollup/src/finalisers/es6' {
  declare module.exports: any;
}

declare module 'rollup/src/finalisers/iife' {
  declare module.exports: any;
}

declare module 'rollup/src/finalisers/index' {
  declare module.exports: any;
}

declare module 'rollup/src/finalisers/shared/getExportBlock' {
  declare module.exports: any;
}

declare module 'rollup/src/finalisers/shared/getGlobalNameMaker' {
  declare module.exports: any;
}

declare module 'rollup/src/finalisers/shared/getInteropBlock' {
  declare module.exports: any;
}

declare module 'rollup/src/finalisers/umd' {
  declare module.exports: any;
}

declare module 'rollup/src/Module' {
  declare module.exports: any;
}

declare module 'rollup/src/Reference' {
  declare module.exports: any;
}

declare module 'rollup/src/rollup' {
  declare module.exports: any;
}

declare module 'rollup/src/Statement' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/callIfFunction' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/collapseSourcemaps' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/defaults' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/ensureArray' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/error' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/first' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/fs' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/getExportMode' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/getIndentString' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/getLocation' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/makeLegalIdentifier' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/map-helpers' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/normalizePlatform' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/object' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/path' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/promise' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/pureFunctions' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/run' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/sourceMappingURL' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/transform' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/transformBundle' {
  declare module.exports: any;
}

declare module 'rollup/src/utils/validateKeys' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup/bin/handleError.js' {
  declare module.exports: $Exports<'rollup/bin/handleError'>;
}
declare module 'rollup/bin/runRollup.js' {
  declare module.exports: $Exports<'rollup/bin/runRollup'>;
}
declare module 'rollup/bin/showHelp.js' {
  declare module.exports: $Exports<'rollup/bin/showHelp'>;
}
declare module 'rollup/dist/rollup.browser.js' {
  declare module.exports: $Exports<'rollup/dist/rollup.browser'>;
}
declare module 'rollup/dist/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/rollup'>;
}
declare module 'rollup/src/ast/attachScopes.js' {
  declare module.exports: $Exports<'rollup/src/ast/attachScopes'>;
}
declare module 'rollup/src/ast/conditions.js' {
  declare module.exports: $Exports<'rollup/src/ast/conditions'>;
}
declare module 'rollup/src/ast/create.js' {
  declare module.exports: $Exports<'rollup/src/ast/create'>;
}
declare module 'rollup/src/ast/extractNames.js' {
  declare module.exports: $Exports<'rollup/src/ast/extractNames'>;
}
declare module 'rollup/src/ast/flatten.js' {
  declare module.exports: $Exports<'rollup/src/ast/flatten'>;
}
declare module 'rollup/src/ast/isFunctionDeclaration.js' {
  declare module.exports: $Exports<'rollup/src/ast/isFunctionDeclaration'>;
}
declare module 'rollup/src/ast/isReference.js' {
  declare module.exports: $Exports<'rollup/src/ast/isReference'>;
}
declare module 'rollup/src/ast/modifierNodes.js' {
  declare module.exports: $Exports<'rollup/src/ast/modifierNodes'>;
}
declare module 'rollup/src/ast/Scope.js' {
  declare module.exports: $Exports<'rollup/src/ast/Scope'>;
}
declare module 'rollup/src/banner.js' {
  declare module.exports: $Exports<'rollup/src/banner'>;
}
declare module 'rollup/src/Bundle.js' {
  declare module.exports: $Exports<'rollup/src/Bundle'>;
}
declare module 'rollup/src/Declaration.js' {
  declare module.exports: $Exports<'rollup/src/Declaration'>;
}
declare module 'rollup/src/ExternalModule.js' {
  declare module.exports: $Exports<'rollup/src/ExternalModule'>;
}
declare module 'rollup/src/finalisers/amd.js' {
  declare module.exports: $Exports<'rollup/src/finalisers/amd'>;
}
declare module 'rollup/src/finalisers/cjs.js' {
  declare module.exports: $Exports<'rollup/src/finalisers/cjs'>;
}
declare module 'rollup/src/finalisers/es6.js' {
  declare module.exports: $Exports<'rollup/src/finalisers/es6'>;
}
declare module 'rollup/src/finalisers/iife.js' {
  declare module.exports: $Exports<'rollup/src/finalisers/iife'>;
}
declare module 'rollup/src/finalisers/index.js' {
  declare module.exports: $Exports<'rollup/src/finalisers/index'>;
}
declare module 'rollup/src/finalisers/shared/getExportBlock.js' {
  declare module.exports: $Exports<'rollup/src/finalisers/shared/getExportBlock'>;
}
declare module 'rollup/src/finalisers/shared/getGlobalNameMaker.js' {
  declare module.exports: $Exports<'rollup/src/finalisers/shared/getGlobalNameMaker'>;
}
declare module 'rollup/src/finalisers/shared/getInteropBlock.js' {
  declare module.exports: $Exports<'rollup/src/finalisers/shared/getInteropBlock'>;
}
declare module 'rollup/src/finalisers/umd.js' {
  declare module.exports: $Exports<'rollup/src/finalisers/umd'>;
}
declare module 'rollup/src/Module.js' {
  declare module.exports: $Exports<'rollup/src/Module'>;
}
declare module 'rollup/src/Reference.js' {
  declare module.exports: $Exports<'rollup/src/Reference'>;
}
declare module 'rollup/src/rollup.js' {
  declare module.exports: $Exports<'rollup/src/rollup'>;
}
declare module 'rollup/src/Statement.js' {
  declare module.exports: $Exports<'rollup/src/Statement'>;
}
declare module 'rollup/src/utils/callIfFunction.js' {
  declare module.exports: $Exports<'rollup/src/utils/callIfFunction'>;
}
declare module 'rollup/src/utils/collapseSourcemaps.js' {
  declare module.exports: $Exports<'rollup/src/utils/collapseSourcemaps'>;
}
declare module 'rollup/src/utils/defaults.js' {
  declare module.exports: $Exports<'rollup/src/utils/defaults'>;
}
declare module 'rollup/src/utils/ensureArray.js' {
  declare module.exports: $Exports<'rollup/src/utils/ensureArray'>;
}
declare module 'rollup/src/utils/error.js' {
  declare module.exports: $Exports<'rollup/src/utils/error'>;
}
declare module 'rollup/src/utils/first.js' {
  declare module.exports: $Exports<'rollup/src/utils/first'>;
}
declare module 'rollup/src/utils/fs.js' {
  declare module.exports: $Exports<'rollup/src/utils/fs'>;
}
declare module 'rollup/src/utils/getExportMode.js' {
  declare module.exports: $Exports<'rollup/src/utils/getExportMode'>;
}
declare module 'rollup/src/utils/getIndentString.js' {
  declare module.exports: $Exports<'rollup/src/utils/getIndentString'>;
}
declare module 'rollup/src/utils/getLocation.js' {
  declare module.exports: $Exports<'rollup/src/utils/getLocation'>;
}
declare module 'rollup/src/utils/makeLegalIdentifier.js' {
  declare module.exports: $Exports<'rollup/src/utils/makeLegalIdentifier'>;
}
declare module 'rollup/src/utils/map-helpers.js' {
  declare module.exports: $Exports<'rollup/src/utils/map-helpers'>;
}
declare module 'rollup/src/utils/normalizePlatform.js' {
  declare module.exports: $Exports<'rollup/src/utils/normalizePlatform'>;
}
declare module 'rollup/src/utils/object.js' {
  declare module.exports: $Exports<'rollup/src/utils/object'>;
}
declare module 'rollup/src/utils/path.js' {
  declare module.exports: $Exports<'rollup/src/utils/path'>;
}
declare module 'rollup/src/utils/promise.js' {
  declare module.exports: $Exports<'rollup/src/utils/promise'>;
}
declare module 'rollup/src/utils/pureFunctions.js' {
  declare module.exports: $Exports<'rollup/src/utils/pureFunctions'>;
}
declare module 'rollup/src/utils/run.js' {
  declare module.exports: $Exports<'rollup/src/utils/run'>;
}
declare module 'rollup/src/utils/sourceMappingURL.js' {
  declare module.exports: $Exports<'rollup/src/utils/sourceMappingURL'>;
}
declare module 'rollup/src/utils/transform.js' {
  declare module.exports: $Exports<'rollup/src/utils/transform'>;
}
declare module 'rollup/src/utils/transformBundle.js' {
  declare module.exports: $Exports<'rollup/src/utils/transformBundle'>;
}
declare module 'rollup/src/utils/validateKeys.js' {
  declare module.exports: $Exports<'rollup/src/utils/validateKeys'>;
}
