// flow-typed signature: 3f1fca5811d3d5ce81a0ac172ee49500
// flow-typed version: <<STUB>>/rollup-plugin-uglify_v0.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-uglify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-uglify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-uglify/dist/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-uglify/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-uglify/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-uglify/dist/index'>;
}
declare module 'rollup-plugin-uglify/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-uglify/src/index'>;
}
