import A from './A'
import B from './B'
import H1 from './H1'
import H2 from './H2'
import H3 from './H3'
import H4 from './H4'
import H5 from './H5'
import Li from './Li'
import Ol from './Ol'
import P from './P'
import I from './I'
import Code from './Code'
import Quote from './Quote'
import Info from './Info'

export { A, B, H1, H2, H3, H4, H5, Li, Ol, P, I, Code, Quote, Info }
